name: ase-lmdb
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - ase=3.25.0
  - asttokens=3.0.0
  - bibtexparser=1.4.3
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - flask=3.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - future=1.0.0
  - graphite2=1.3.14
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - latexcodec=2.0.1
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.8
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - monty=2025.3.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=2.0.1
  - networkx=3.5
  - openjpeg=2.5.3
  - openssl=3.5.2
  - orjson=3.11.1
  - packaging=25.0
  - palettable=3.3.3
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - plotly=6.2.0
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pybtex=0.25.1
  - pycparser=2.22
  - pygments=2.19.2
  - pymatgen=2025.6.14
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - requests=2.32.4
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - scipy=1.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - spglib=2.6.0
  - stack_data=0.6.3
  - tabulate=0.9.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uncertainties=3.2.3
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - ase-db-backends==0.10.0
      - cloudpickle==3.1.1
      - clusterscope==0.0.10
      - cryptography==45.0.6
      - e3nn==0.5.6
      - fairchem-core==2.3.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - huggingface-hub==0.34.3
      - hydra-core==1.3.2
      - llvmlite==0.44.0
      - lmdb==1.7.3
      - markdown==3.8.2
      - mypy-extensions==1.1.0
      - numba==0.61.2
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - platformdirs==4.3.8
      - protobuf==6.31.1
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pymysql==1.1.1
      - pyre-extensions==0.0.32
      - sentry-sdk==2.34.1
      - smmap==5.0.2
      - submitit==1.5.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torchtnt==0.2.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - wandb==0.21.0
